#!/bin/bash

if [ ! -e $JAVA_HOME ]; then
    echo "[ERROR] $JAVA_HOME not exist"
    exit -3
fi

BASE_BIN_DIR=`dirname $0`

$JAVA_HOME/bin/java -cp $BASE_BIN_DIR/htree_lib/htree.jar me.hatter.tool.HTree $@
