#!/bin/bash

echo "+-------------------------------------------------+"
echo "| Hatter Jiang's Java Profiler Tool               |"
echo "| Profile Java Stack                              |"
echo "|                                                 |"
echo "|                         Hatter Jiang(1983-2012) |"
echo "|                            URL http://hatter.me |"
echo "+-------------------------------------------------+"

if [ ! -e $JAVA_HOME ]; then
    echo "[ERROR] $JAVA_HOME not exist"
    exit -3
fi

if [ $# == 0 ]; then
  echo "Analysis java stack data."
  echo ""
  echo "Usage:"
  echo "jprofiler JPID"
  echo ""
  exit -1
fi

BASE_BIN_DIR=`dirname $0`

$JAVA_HOME/bin/java -cp $BASE_BIN_DIR/jstackprofiler/jstackprofiler.jar me.hatter.jprofiler.main.JStackProfiler $@

