#!/bin/bash

echo "+-------------------------------------------------+"
echo "| Hatter Jiang's Java Profiler Tool               |"
echo "| Dump Java Stack                                 |"
echo "|                                                 |"
echo "|                         Hatter Jiang(1983-2012) |"
echo "|                            URL http://hatter.me |"
echo "+-------------------------------------------------+"

if [ ! -e $JAVA_HOME ]; then
    echo "[ERROR] $JAVA_HOME not exist"
    exit -3
fi

if [ $# == 0 ]; then
  echo "Dump java stack data."
  echo ""
  echo "Usage:"
  echo "jdumpstack JPID [DUMP TIME(S)] [SLEEP SECONDS]"
  echo ""
  exit -1
fi

if [ ! "`$JAVA_HOME/bin/jps | grep -w \"^$1\"`" ]; then
  echo "[ERROR] JPID not found!"
  exit -2
fi

dumpTimes=10
if [ $2 ]; then
  dumpTimes=$2;
fi

sleepSeconds=0
if [ $3 ]; then
  sleepSeconds=$3
fi

for ((i=0; i<$dumpTimes; i++))
do
  if [ $i -gt 0 ]; then
    if [ $sleepSeconds -gt 0 ]; then
      echo "[INFO] Sleep $sleepSeconds s"
      sleep $sleepSeconds
    fi
  fi
  echo "[INFO] Dump JPID=$1 ($i)"
  $JAVA_HOME/bin/jstack $1 > "jstack_$1.$i"
done

